#!/bin/bash
# Moar bip on https://github.com/NaWer/beep

# Author : PlasticHat
# Source : http://blog.dhampir.no/content/fun-with-beep
beep    -f 987 -l 53   -d 53  \
     -n -f 987 -l 53   -d 53  \
     -n -f 987 -l 53   -d 53  \
     -n -f 987 -l 428         \
     -n -f 784 -l 428         \
     -n -f 880 -l 428         \
     -n -f 987 -l 107  -d 214 \
     -n -f 880 -l 107         \
     -n -f 987 -l 857         \
     -n -f 740 -l 428         \
     -n -f 659 -l 428         \
     -n -f 740 -l 428         \
     -n -f 659 -l 107  -d 107 \
     -n -f 880 -l 428         \
     -n -f 880 -l 107  -d 107 \
     -n -f 830 -l 428         \
     -n -f 880 -l 107  -d 107 \
     -n -f 830 -l 428         \
     -n -f 830 -l 107  -d 107 \
     -n -f 740 -l 428         \
     -n -f 659 -l 428         \
     -n -f 622 -l 428         \
     -n -f 659 -l 107  -d 107 \
     -n -f 554 -l 1714        \
     -n -f 740 -l 428         \
     -n -f 659 -l 428         \
     -n -f 740 -l 428         \
     -n -f 659 -l 107  -d 107 \
     -n -f 880 -l 428         \
     -n -f 880 -l 107  -d 107 \
     -n -f 830 -l 428         \
     -n -f 880 -l 107  -d 107 \
     -n -f 830 -l 428         \
     -n -f 830 -l 107  -d 107 \
     -n -f 740 -l 428         \
     -n -f 659 -l 428         \
     -n -f 740 -l 428         \
     -n -f 880 -l 107  -d 107 \
     -n -f 987 -l 1714