#!/bin/bash
# Moar bip on https://github.com/NaWer/beep

# Author : Jake
# Source : http://kirrus.co.uk/2010/09/linux-beep-music/
beep    -f 880     -l 500  -D 70 \
     -n -f 587.33  -l 1000 -D 70 \
     -n -f 698.46  -l 500  -D 70 \
     -n -f 880     -l 500  -D 70 \
     -n -f 587.33  -l 1000 -D 70 \
     -n -f 698.46  -l 500  -D 70 \
     -n -f 880     -l 250  -D 70 \
     -n -f 1046.50 -l 250  -D 70 \
     -n -f 987.77  -l 500  -D 70 \
     -n -f 783.99  -l 500  -D 70 \
     -n -f 698.46  -l 250  -D 70 \
     -n -f 783.99  -l 250  -D 70 \
     -n -f 880     -l 500  -D 70 \
     -n -f 587.33  -l 500  -D 70 \
     -n -f 523.25  -l 250  -D 70 \
     -n -f 659.26  -l 250  -D 70 \
     -n -f 587.33  -l 750