#!/bin/bash
# Moar bip on https://github.com/NaWer/beep

# Author : AnoPoli
# Source : http://ubuntuforums.org/showthread.php?t=1157670&page=4&p=9468252#post9468252
for i in {21..3500..40}
do
     beep -f $i -d 20 -l 20
done
for i in {3500..21..40}
do
     beep -f $i -d 20 -l 20
done